### ISSUE TITLE
Code/Output Blocks should be formatted by default with JuliaMono font

### ISSUE THREAD

**Issue by storopoli** [rikhuijzer/Books.jl#135]
How to insert this is documented in [JuliaMono FAQ Page](https://juliamono.netlify.app/faq/#how_can_i_use_the_web_fonts):

<details>
<summary>Click to expand</summary>

1. Option 1 (using the jsdelivr content delivery network):

```css
@font-face {
    font-family: JuliaMono-Regular;
    src: url("https://cdn.jsdelivr.net/gh/cormullion/juliamono/webfonts/JuliaMono-Regular.woff2");
}
```

2. Option 2 (using the cdnjs content delivery network):

```css
@font-face {
    font-family: JuliaMono-Regular;
    src: url("https://cdnjs.cloudflare.com/ajax/libs/juliamono/0.037/JuliaMono-Regular.woff2");
}
```

Then, in the area of the CSS where you control the appearance of monospaced text:

```css
pre {
    font-family: JuliaMono-Regular;
}
code {
    font-family: JuliaMono-Regular;
    }
```
> Notice that the CDNJS version points to a specific version (e.g. v0.037 here), whereas the JSDELIVR version always retrieves the current master version.

You may prefer to serve the WOFF/2 fonts from your own server. One problem you might encounter is related to Cross-origin resource sharing, which on some browsers prevents one web page from downloading fonts from another.

</details>
